### ISSUE TITLE
probleme communication : reponse vide + probleme communication : reponse vide 

### ISSUE THREAD

**Issue by besi** [christianDUCROS/ld2410-human_sensor#1]
Bonjour monsieur :-)

I have a LD2450 sensor and using your library I could successfully read the firmware version. So it seems that the UART communication seems to work.

However. I don't manage to detect anything and I keep getting the output:

> error, frame header is incorrect
> pas de présence humaine

If I run your code (with only the pins changed) then I get the following output:
```

-----------CONFIGURATION----------------
UART(1, baudrate=256000, bits=8, parity=None, stop=1, tx=12, rx=13, rts=-1, cts=-1, txbuf=256, rxbuf=256, timeout=1, timeout_char=0)
----------------------------------------
enable config success
probleme communication : reponse vide 
Maximum_distance_gate_and_unoccupied_duration_parameters_configuration failure
probleme communication : reponse vide 
distance_gate_sensitivity_configuration failure
probleme communication : reponse vide 
Distance_resolution_setting failure 
end config success
-----------DECTECTION----------------
error, frame header is incorrect
pas de présence humaine
```

This is my code. I added `invert = 0` and `timeout_char = 1` to match the result in your video.

```python
# HLK-LD2410 B et C  (Microwave-based human/object presence sensor) 
#rev 1 DUCROS christian janvier 2024 à partir du fichier 
#rev 1 - shabaz - May 2023

#programme principal
from machine import Pin, UART
import utime
import ld2410

#led if human_detection
# board LED on the Pi Pico is 25
# board LED on the Pico W is 'LED'
boardled = Pin(33, Pin.OUT)
boardled.off()

print('-----------CONFIGURATION----------------')
uart1 = UART(1, baudrate = 256000, tx=Pin(12), rx=Pin(13), timeout = 1, timeout_char = 0, invert = 0)
print(uart1)

human_sensor = ld2410.LD2410(uart1)
print('----------------------------------------')
human_sensor.enable_config()
human_sensor.Maximum_distance_gate_and_unoccupied_duration_parameters_configuration(2,2,50) # 2-->8,2-->8,0-->65535 
#human_sensor.read_parameter()
human_sensor.distance_gate_sensitivity_configuration(1,4,4)
#human_sensor.read_firmware_version()
#human_sensor.set_serial_port_baud_rate(0x0007) #0007 --> 256000 ,  0x0005-->115200
#human_sensor.restore_factory_settings()
#human_sensor.reboot_module() #--> end_config failure
#human_sensor.bluetooth_setting(0x0001)  #0x0001-->ON 0x0000-->OFF 
#human_sensor.get_mac_address()
#human_sensor.set_bluetooth_password()
human_sensor.distance_resolution_setting(0x0000)
#human_sensor.query_distance_resolution_setting()
human_sensor.end_config()

#human_sensor.enable_engineering_mode()
#human_sensor.end_engineering_mode()

utime.sleep(5) #debug pour lire les rapports de configuration

print('-----------DECTECTION----------------')
while True: 
    human_sensor.send_command_report_data()
    #human_sensor.print_meas()
    human_sensor.human_detection(boardled,50,50)
    utime.sleep(3)

```

If I don't do certain configs I get success only:

```python
human_sensor.enable_config()
#human_sensor.Maximum_distance_gate_and_unoccupied_duration_parameters_configuration(2,2,50) # 2-->8,2-->8,0-->65535 
human_sensor.read_firmware_version()
human_sensor.get_mac_address()
human_sensor.end_config()
```

> ```
> ----------------------------------------
> enable config success
> firmware :V 2 . 4 . 23 10 19 15
> MAc Address f7 99 9b 63 f7 92
> end config success
> -----------DECTECTION----------------
> error, frame header is incorrect
> pas de présence humaine
> error, frame header is in
> ```

**Comment by christianDUCROS** [comment]
B‌onjour
Je viens de relire votre mail. 
Il faudrait que je refasse un essai mais je n'ai pas trop le temps pour le moment (je travaille sur les projets de mes élèves)
je serai en vacances la semaine prochaine. Je vais refaire un essai .
En tout cas il faut analyser la trame pour comprendre le problème. Si l'entête ne correspond pas récupérer la trame. 
Cdt    
 

De : "Besi" ***@***.***>
A : "christianDUCROS/ld2410-human_sensor" ***@***.***>,"Subscribed" ***@***.***>
Envoyé: vendredi 12 Avril 2024 15:16
Objet : Re: [christianDUCROS/ld2410-human_sensor] probleme communication : reponse vide + probleme communication : reponse vide (Issue #1)
 

 

Bonjour monsieur :-)

I have a LD2450 sensor and using your library I could successfully read the firmware version. So it seems that the UART communication seems to work.

However. I don't manage to detect anything and I keep getting the output:


error, frame header is incorrect
pas de présence humaine


If I run your code (with only the pins changed) then I get the following output:


-----------CONFIGURATION----------------
UART(1, baudrate=256000, bits=8, parity=None, stop=1, tx=12, rx=13, rts=-1, cts=-1, txbuf=256, rxbuf=256, timeout=1, timeout_char=0)
----------------------------------------
enable config success
probleme communication : reponse vide 
Maximum_distance_gate_and_unoccupied_duration_parameters_configuration failure
probleme communication : reponse vide 
distance_gate_sensitivity_configuration failure
probleme communication : reponse vide 
Distance_resolution_setting failure 
end config success
-----------DECTECTION----------------
error, frame header is incorrect
pas de présence humaine


This is my code. I added invert = 0 and timeout_char = 1 to match the result in your video.


# HLK-LD2410 B et C  (Microwave-based human/object presence sensor) 
#rev 1 DUCROS christian janvier 2024 à partir du fichier 
#rev 1 - shabaz - May 2023

#programme principal
from machine import Pin, UART
import utime
import ld2410

#led if human_detection
# board LED on the Pi Pico is 25
# board LED on the Pico W is 'LED'
boardled = Pin(33, Pin.OUT)
boardled.off()

print('-----------CONFIGURATION----------------')
uart1 = UART(1, baudrate = 256000, tx=Pin(12), rx=Pin(13), timeout = 1, timeout_char = 0, invert = 0)
print(uart1)

human_sensor = ld2410.LD2410(uart1)
print('----------------------------------------')
human_sensor.enable_config()
human_sensor.Maximum_distance_gate_and_unoccupied_duration_parameters_configuration(2,2,50) # 2-->8,2-->8,0-->65535 
#human_sensor.read_parameter()
human_sensor.distance_gate_sensitivity_configuration(1,4,4)
#human_sensor.read_firmware_version()
#human_sensor.set_serial_port_baud_rate(0x0007) #0007 --> 256000 ,  0x0005-->115200
#human_sensor.restore_factory_settings()
#human_sensor.reboot_module() #--> end_config failure
#human_sensor.bluetooth_setting(0x0001)  #0x0001-->ON 0x0000-->OFF 
#human_sensor.get_mac_address()
#human_sensor.set_bluetooth_password()
human_sensor.distance_resolution_setting(0x0000)
#human_sensor.query_distance_resolution_setting()
human_sensor.end_config()

#human_sensor.enable_engineering_mode()
#human_sensor.end_engineering_mode()

utime.sleep(5) #debug pour lire les rapports de configuration

print('-----------DECTECTION----------------')
while True: 
    human_sensor.send_command_report_data()
    #human_sensor.print_meas()
    human_sensor.human_detection(boardled,50,50)
    utime.sleep(3)


If I don't do certain configs I get success only:


human_sensor.enable_config()
#human_sensor.Maximum_distance_gate_and_unoccupied_duration_parameters_configuration(2,2,50) # 2-->8,2-->8,0-->65535 
human_sensor.read_firmware_version()
human_sensor.get_mac_address()
human_sensor.end_config()



----------------------------------------
enable config success
firmware :V 2 . 4 . 23 10 19 15
MAc Address f7 99 9b 63 f7 92
end config success
-----------DECTECTION----------------
error, frame header is incorrect
pas de présence humaine
error, frame header is in

**Comment by besi** [comment]
I did realise that the sensor I use has another format so LD2450 and LD2410 behave different...
Your library works very well with the new sensor I got. So thanks very much.
